In [260]:
import torch

In [261]:
import sys
sys.path.append('..')

In [262]:
import torchvision
import torchvision.transforms as transforms
import numpy as np
def create_train_dataset(batch_size = 128, root = '../experiments/MNIST/data/'):

    transform_train = transforms.Compose([
     transforms.ToTensor(),
    ])
    trainset = torchvision.datasets.MNIST(root=root, train=True, download=True, transform=transform_train)
    trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True, num_workers=2)

    return trainloader
def create_test_dataset(batch_size = 128, root = '../experiments/MNIST/data/'):
    transform_test = transforms.Compose([
     transforms.ToTensor(),
    ])
    testset = torchvision.datasets.MNIST(root=root, train=False, download=True, transform=transform_test)
    testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=False, num_workers=2)
    return testloader

In [263]:
ds_train = create_train_dataset(128)
ds_val = create_test_dataset(128)

In [210]:
len(ds_train.dataset)

60000

In [77]:
from lib.base_model.small_cnn import SmallCNN

In [264]:
net = SmallCNN()

In [265]:
for (data, label) in ds_train:
    print(data.size())
    print(label.size())
    break

torch.Size([128, 1, 28, 28])
torch.Size([128])


In [267]:
data.size()

torch.Size([128, 1, 28, 28])

In [276]:
label = label.reshape(-1,1)

In [277]:
label.size()

torch.Size([128, 1])

In [268]:
ret = net(data)

In [273]:
q = ret.max(1, keepdim=True)[1]

In [279]:
w = q.eq(label)

In [280]:
w.size()

torch.Size([128, 1])

In [283]:
x = torch.tensor([False, True, False, True]).reshape(-1, 1)
y = torch.tensor([True, True, False, False]).reshape(-1, 1)

In [284]:
x

tensor([[False],
        [ True],
        [False],
        [ True]])

In [286]:
z = torch.logical_xor(x,y)

In [287]:
a = torch.logical_and(x,z)

In [290]:
a.type(torch.int)

tensor([[0],
        [0],
        [0],
        [1]], dtype=torch.int32)

In [48]:
for (data, label) in ds_train:
    print(data.size())
    print(label.size())
    break

torch.Size([128, 1, 28, 28])
torch.Size([128])


In [83]:
label

tensor([8, 8, 7, 2, 6, 1, 8, 3, 7, 6, 4, 8, 2, 3, 3, 1, 2, 4, 0, 7, 9, 3, 1, 3,
        4, 7, 7, 9, 4, 7, 1, 6, 9, 6, 1, 6, 8, 3, 0, 6, 1, 7, 3, 7, 8, 7, 8, 9,
        3, 8, 6, 7, 6, 7, 3, 1, 2, 4, 7, 3, 6, 1, 5, 3, 1, 7, 0, 6, 4, 1, 0, 6,
        8, 2, 3, 1, 0, 1, 9, 6, 8, 9, 2, 9, 4, 5, 2, 4, 4, 4, 0, 0, 4, 2, 6, 8,
        1, 8, 1, 7, 6, 6, 4, 2, 5, 0, 7, 0, 0, 4, 8, 7, 6, 1, 5, 1, 7, 0, 5, 1,
        5, 5, 4, 9, 5, 9, 1, 1])

In [84]:
data.dtype

torch.float32

In [12]:
x = torch.rand((128,1,28,28))

In [19]:
x.dtype

torch.float32

In [85]:
y = data[0].reshape(-1,1,28,28)

In [87]:
y.shape

torch.Size([1, 1, 28, 28])

In [88]:
z = y.repeat(10,1,1,1)

In [89]:
z.size()

torch.Size([10, 1, 28, 28])

In [146]:
noise = torch.rand(z.size()) # [0, 1]

In [147]:
noise.size()

torch.Size([10, 1, 28, 28])

In [162]:
fake = torch.clamp(z+noise*0.1, 0,1)

In [163]:
net = net.cpu()

In [164]:
output = net(fake)

In [165]:
output.size()

torch.Size([10, 10])

In [166]:
label[0]

tensor(8)

In [167]:
output

tensor([[-1.4896e+00, -2.8341e+00, -1.3239e+00,  1.5325e+00, -1.9309e+00,
         -3.6158e+00, -5.0520e+00, -3.4473e+00,  1.4083e+01,  4.0771e+00],
        [ 1.6583e+00, -1.2646e+00, -3.8357e-01, -2.8781e+00, -2.5909e+00,
         -5.3374e-01,  7.2802e-01, -3.5819e+00,  9.0035e+00, -1.5796e-01],
        [ 5.7235e-01, -3.2440e-01, -1.5596e+00,  8.3549e-01, -6.2726e+00,
          3.7495e+00,  2.2526e+00, -8.9635e+00,  1.1271e+01, -1.5623e+00],
        [-9.3803e-01,  8.9125e-01, -3.3351e+00,  6.6470e-01, -6.3040e+00,
          2.1549e+00, -3.0597e+00, -3.5271e+00,  1.3877e+01, -4.2543e-01],
        [-9.9089e-01, -4.0398e+00,  1.3096e+00, -9.7710e-02, -2.8479e+00,
         -3.9337e+00, -2.8700e+00, -2.4094e+00,  1.4971e+01,  9.0807e-01],
        [-4.0733e+00,  1.7080e-01,  3.4797e+00,  4.0547e+00, -4.7990e+00,
         -2.5838e+00, -4.5276e+00, -2.6387e+00,  1.0805e+01,  1.1128e-01],
        [-1.0745e+00, -1.1971e+00,  2.1102e+00,  2.7501e+00, -4.7975e+00,
         -2.6232e+00, -2.1360e+0

In [176]:
_,ret = output.max(1)

In [179]:
m = ret.eq(torch.tensor([8, 8, 8, 8, 1, 1, 8, 8, 8, 8]))

In [180]:
m.size()

torch.Size([10])

In [97]:
t = torch.rand(20,10)

In [100]:
t.max(1).indices.size()

torch.Size([20])

In [106]:
net.load_state_dict(torch.load('../experiments/MNIST/YOPO-5-10/log/models/last.checkpoint', map_location='cuda:0')['state_dict'])

<All keys matched successfully>

In [170]:
output.item()

ValueError: only one element tensors can be converted to Python scalars

In [171]:
output.size()

torch.Size([10, 10])

In [173]:
q = torch.zeros((output.size(0), 1))

In [174]:
q.size()

torch.Size([10, 1])

In [182]:
m = m.reshape(q.size())

In [186]:
z = q+m

In [185]:
m.size()

torch.Size([10, 1])

In [190]:
torch.cat((z,z), axis=0)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [193]:
z.eq(1).sum()

tensor(8)

In [194]:
t = torch.tensor([1,5,3,6,8,4,2,6,0,0,1,2,4])

In [196]:
t = t.reshape(-1,1)

In [197]:
t.shape

torch.Size([13, 1])

In [205]:
ret = t.flatten().sort()

In [206]:
ret

torch.return_types.sort(
values=tensor([0, 0, 1, 1, 2, 2, 3, 4, 4, 5, 6, 6, 8]),
indices=tensor([ 8,  9,  0, 10, 11,  6,  2,  5, 12,  1,  7,  3,  4]))

In [208]:
ret.indices

tensor([ 8,  9,  0, 10, 11,  6,  2,  5, 12,  1,  7,  3,  4])

In [212]:
net.zero_grad()

In [213]:
import torch.nn.functional as F

In [234]:
target = None
for (image, targets) in ds_train:
    print(targets.size())
    target = targets
    outputs = net(image)
    loss = F.cross_entropy(outputs, targets)
    loss.backward()
    break

torch.Size([128])


In [236]:
target.view(1, -1).shape

torch.Size([1, 128])

In [219]:
for layer in net._modules:
    print(layer)

conv1
layer_one
feature_extractor
classifier
other_layers


In [229]:
for t1,t2 in zip(net.parameters(), net.state_dict().items()):
    print(t2[0])

conv1.weight
conv1.bias
layer_one.conv1.weight
layer_one.conv1.bias
feature_extractor.conv2.weight
feature_extractor.conv2.bias
feature_extractor.conv3.weight
feature_extractor.conv3.bias
feature_extractor.conv4.weight
feature_extractor.conv4.bias
classifier.fc1.weight
classifier.fc1.bias
classifier.fc2.weight
classifier.fc2.bias


In [237]:
x = torch.randn(2, 1, 1)#为1可以扩展为3和3 
y = torch.randn(2, 3, 3)

In [240]:
x.size()

torch.Size([2, 1, 1])

In [241]:
y.size()

torch.Size([2, 3, 3])

In [242]:
x = x.expand_as(y)

In [243]:
x.size()

torch.Size([2, 3, 3])

In [244]:
x

tensor([[[0.4926, 0.4926, 0.4926],
         [0.4926, 0.4926, 0.4926],
         [0.4926, 0.4926, 0.4926]],

        [[0.3515, 0.3515, 0.3515],
         [0.3515, 0.3515, 0.3515],
         [0.3515, 0.3515, 0.3515]]])

In [247]:
x.sum(dim=0).size()

torch.Size([3, 3])

In [248]:
x = torch.randn(5,128)

In [254]:
x.shape

torch.Size([5, 128])

In [252]:
x.view(-1).size()

torch.Size([640])

In [256]:
x.flatten().size()

torch.Size([640])

In [258]:
x = torch.tensor([1,0,1,1])

In [259]:
x.bool()

tensor([ True, False,  True,  True])